server:
  port: 9090

spring:
  mail:
    host: smtp.qq.com # 配置 smtp 服务器地址
    port: 587 # smtp 服务器的端口
    username: 9999999@qq.com # 配置邮箱用户名(你的邮箱地址)
    password: 9999999   # 配置申请到的授权码(刚让复制的授权码)
    default-encoding: UTF-8 # 配置邮件编码
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory # 配饰 SSL 加密工厂
          timeout: 30000
          connectiontimeout: 30000
        #          writetimeout: 1
        debug: true
    from: 9999999@qq.com # 发送方邮件，陪在yml中可方便更改
  application:
    name: my-practice
#  cloud:
#    discovery:
#      register: true
#    loadbalancer:
#      ribbon:
#        enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/practice?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: 123456
      auto-commit: true
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 8
      minimum-idle: 8
      pool-name: HikariCP-financial
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0ms

  main:
    allow-bean-definition-overriding: false

  kafka:
    topic: test
    bootstrap-servers: 127.0.0.1:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      bootstrap-servers: 127.0.0.1:9092
#      retries: 3
#    consumer:
#      group-id: default_consumer_group #群组ID
#      enable-auto-commit: true
#      auto-commit-interval: 1000
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


# mybatis配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 注意更新策略，默认空值、null值不更新
      update-strategy: not_empty
  mapper-locations: classpath:mapper/*.xml

auth:
  exp: 3600000
  secret: s/*-.1263@
  issuer: my-practice





